# Build SPM covariate table

In [154]:
import pandas as pd
import numpy as np
from pathlib import Path

## 1) Paths and column names
Adjust these to your files/sheet names if needed.

In [155]:
base = "C:/Users/juhoffmann/Desktop/SubliminalVideoPriming/"
out_path_regressor = Path(base) / "scripts/mri/rt_fmri_analysis/regressors.csv"
out_path_missing = Path(base) / "scripts/mri/rt_fmri_analysis/rt_missing_subjects.txt"
out_path_patient = Path(base) / "scripts/mri/medication_severity_effect_MDD/patient_subjects.txt"

cov_path = f"{base}data/demographics/all.xlsx"
cov_sheet = 0

spm_path = f"{base}data/mri/SPM_mat_subject_row.xlsx"
spm_sheet = 0

rt_path = f"{base}data/formatted/reaction_times_long_format.csv"

cov = pd.read_excel(cov_path, sheet_name=cov_sheet)
rt = pd.read_csv(rt_path)
spm = pd.read_excel(spm_path, sheet_name=spm_sheet)
rt.rename(columns={"Participant": "ID", "ReactionTime": "rt"}, inplace=True)

cov.head()
spm.head()
#rt.head()

        ID       contrast
0  sub-004  con_0001.nii'
1  sub-006  con_0001.nii'
2  sub-010  con_0001.nii'
3  sub-011  con_0001.nii'
4  sub-014  con_0001.nii'

In [156]:
def normalize_id(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    x = x.replace("Sub-", "sub-").replace("SUB-", "sub-").replace("sub_", "sub-")
    digits = "".join([c for c in x if c.isdigit()])
    return f"sub-{digits.zfill(3)}" if digits else x

cov = cov.replace({"na": np.nan, "NA": np.nan, "": np.nan})
cov["ID"] = cov["ID"].apply(normalize_id)
rt["ID"] = rt["ID"].apply(normalize_id)
spm["ID"] = spm["ID"].apply(normalize_id)

# Derive condition from SPM sheet if needed
if "Condition" in spm.columns:
    spm["Condition"] = spm["Condition"].astype(str).str.strip().str.lower()
elif "contrast" in spm.columns:
    contrast_clean = spm["contrast"].astype(str).str.strip().str.replace("'", "", regex=False)
    contrast_map = {
        "con_0001.nii": "happy_happy",
        "con_0002.nii": "happy_sad",
        "con_0003.nii": "sad_happy",
        "con_0004.nii": "sad_sad",
    }
    spm["Condition"] = contrast_clean.map(contrast_map)
    spm["Condition"] = spm["Condition"].astype(str).str.strip().str.lower()
cov.head()

C:\Users\juhoffmann\AppData\Local\Temp\ipykernel_7852\700581199.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cov = cov.replace({"na": np.nan, "NA": np.nan, "": np.nan})

,EmoCon_ID,ID,Antidepressants,Video Mask done,Gender_x,Alter,Gender_f1_m2,Group_MDD1_HC2,BVAQ,BDI-II,...,CERQ_Rumination,CERQ_Positive Refokussierung,CERQ_Refokussierung auf Planung,CERQ_Positive Neubewertung,CERQ_Relativieren,CERQ_Katastrophisierung,CERQ_Andere Beschuldigen,Antidepressants.1,Medication,AD_Classes
0,EmoCon006,sub-004,0.0,1,male,29,2,2,56,6,...,8.0,11.0,17.0,13.0,15.0,7.0,7.0,NaN,NaN,NaN
1,EmoCon007,sub-006,0.0,1,female,23,1,2,47,3,...,12.0,11.0,14.0,16.0,17.0,7.0,10.0,NaN,NaN,NaN
2,EmoCon001,sub-007,1.0,1,male,23,2,1,52,26,...,19.0,4.0,8.0,4.0,7.0,15.0,4.0,1.0,morning: Citalopram 30mg,['SSRI']
3,EmoCon017,sub-008,1.0,1,female,19,1,1,58,35,...,6.0,5.0,13.0,11.0,5.0,9.0,7.0,1.0,morning: Escitalopram 10mg evening: Quetiapin...,['SSRI']
4,EmoCon015,sub-009,1.0,1,male,27,2,1,59,14,...,17.0,5.0,12.0,5.0,4.0,14.0,7.0,1.0,morning: Elontril 300mg,['NDRI']

In [157]:
# Covariate columns from cov_sheet
age_col = "Alter"
gender_col = "Gender_f1_m2"
group_col = "Group_MDD1_HC2"
med_col = "Antidepressants"
bdi_col = "BDI-II"
ham_col = "Hamilton Score"
rt_col = "rt"
spm_id_col = "ID"
cov_id_col = "ID"
rt_id_col = "ID"

### Build analysis covariates

In [158]:
# Recode gender and group if present
if gender_col in cov.columns:
    cov["Gender_f1_m2"] = cov[gender_col].map({1: 0, 2: 1})

if group_col in cov.columns:
    cov["Group_MDD1_HC2"] = cov[group_col].map({1: 0, 2: 1})

if med_col in cov.columns:
    cov["Antidepressants"] = cov[med_col].fillna(0)

# Age and BDI
if age_col in cov.columns:
    cov["Age"] = pd.to_numeric(cov[age_col], errors="coerce")
elif "age" in cov.columns:
    cov["Age"] = pd.to_numeric(cov["age"], errors="coerce")

if bdi_col in cov.columns:
    cov["BDI"] = pd.to_numeric(cov[bdi_col], errors="coerce")

# Center continuous covariates (optional)
if bdi_col in cov.columns:
    cov["BDI_centered"] = cov["BDI"] - cov["BDI"].mean()
if ham_col in cov.columns:
    cov["Hamilton_centered"] = pd.to_numeric(cov[ham_col], errors="coerce") - pd.to_numeric(cov[ham_col], errors="coerce").mean()

cov.head()

,EmoCon_ID,ID,Antidepressants,Video Mask done,Gender_x,Alter,Gender_f1_m2,Group_MDD1_HC2,BVAQ,BDI-II,...,CERQ_Relativieren,CERQ_Katastrophisierung,CERQ_Andere Beschuldigen,Antidepressants.1,Medication,AD_Classes,Age,BDI,BDI_centered,Hamilton_centered
0,EmoCon006,sub-004,0.0,1,male,29,1,1,56,6,...,15.0,7.0,7.0,NaN,NaN,NaN,29,6,-8.302521,NaN
1,EmoCon007,sub-006,0.0,1,female,23,0,1,47,3,...,17.0,7.0,10.0,NaN,NaN,NaN,23,3,-11.302521,NaN
2,EmoCon001,sub-007,1.0,1,male,23,1,0,52,26,...,7.0,15.0,4.0,1.0,morning: Citalopram 30mg,['SSRI'],23,26,11.697479,0.45614
3,EmoCon017,sub-008,1.0,1,female,19,0,0,58,35,...,5.0,9.0,7.0,1.0,morning: Escitalopram 10mg evening: Quetiapin...,['SSRI'],19,35,20.697479,2.45614
4,EmoCon015,sub-009,1.0,1,male,27,1,0,59,14,...,4.0,14.0,7.0,1.0,morning: Elontril 300mg,['NDRI'],27,14,-0.302521,1.45614

### Merge into SPM order and export

In [159]:
# Start from SPM sheet as base
merged = spm.copy()

# Add covariates from demographics
cov_cols = [cov_id_col, "Age", "Antidepressants", "BDI"]
cov_cols = [c for c in cov_cols if c in cov.columns]
merged = merged.merge(cov[cov_cols], left_on=spm_id_col, right_on=cov_id_col, how="left")
if cov_id_col in merged.columns and cov_id_col != spm_id_col:
    merged = merged.drop(columns=[cov_id_col])

# Mean RT per subject and condition
rt_cond = rt.copy()
rt_cond["Condition"] = rt_cond["Condition"].astype(str).str.strip().str.lower()
rt_mean_cond = rt_cond.groupby([rt_id_col, "Condition"], as_index=False)[rt_col].mean()
merged = merged.merge(rt_mean_cond, left_on=[spm_id_col, "Condition"], right_on=[rt_id_col, "Condition"], how="left")
if rt_id_col in merged.columns and rt_id_col != spm_id_col:
    merged = merged.drop(columns=[rt_id_col])

# Select final columns: keep full SPM sheet + new covariates
final_cols = list(spm.columns)
for c in ["Age", "Antidepressants", "BDI", "rt"]:
    if c in merged.columns and c not in final_cols:
        final_cols.append(c)

cov_table = merged[final_cols]
cov_table.head()

        ID       contrast    Condition  Age  Antidepressants  BDI        rt
0  sub-004  con_0001.nii'  happy_happy   29              0.0    6       NaN
1  sub-006  con_0001.nii'  happy_happy   23              0.0    3       NaN
2  sub-010  con_0001.nii'  happy_happy   22              0.0    0  0.599472
3  sub-011  con_0001.nii'  happy_happy   18              0.0    8  0.541878
4  sub-014  con_0001.nii'  happy_happy   26              0.0    0  0.588231

In [160]:
# Drop specific participants
drop_ids = {"sub-016", "sub-119"}
if spm_id_col in cov_table.columns:
    cov_table = cov_table[~cov_table[spm_id_col].isin(drop_ids)]

# Determine subject order from SPM sheet (preserve original row order)
order_ids = spm[spm_id_col].astype(str).tolist()
unique_ids = list(dict.fromkeys(order_ids))

# Mean RT by condition (for completeness checks)
conditions = ["happy_happy", "happy_sad", "sad_happy", "sad_sad"]
rt_cond = rt.copy()
rt_cond["Condition"] = rt_cond["Condition"].astype(str).str.strip().str.lower()
conditions = [c.lower() for c in conditions]
rt_mean_cond = rt_cond.groupby([rt_id_col, "Condition"], as_index=False)[rt_col].mean()
rt_pivot = rt_mean_cond.pivot(index=rt_id_col, columns="Condition", values=rt_col)

missing_subjects = []
for sid in unique_ids:
    if sid not in rt_pivot.index:
        missing_subjects.append(sid)
    else:
        row = rt_pivot.loc[sid]
        if any(pd.isna(row.get(cond)) for cond in conditions):
            missing_subjects.append(sid)

complete_ids = [sid for sid in unique_ids if sid not in missing_subjects]
if missing_subjects:
    print("Removing subjects with missing RT in any condition:", ', '.join(missing_subjects))

    # Output missing subjects with ID/age/gender in provided order
    missing_order_text = """
sub-004	29	2
sub-006	23	1
sub-010	23	2
sub-011	19	1
sub-014	27	2
sub-015	22	1
sub-016	18	2
sub-017	36	2
sub-018	26	2
sub-019	28	2
sub-022	29	2
sub-024	26	2
sub-025	22	1
sub-027	22	1
sub-028	32	1
sub-029	25	1
sub-030	23	1
sub-031	32	2
sub-032	22	2
sub-033	26	2
sub-034	21	2
sub-041	26	2
sub-043	21	1
sub-045	25	2
sub-046	33	1
sub-047	25	1
sub-050	30	1
sub-051	18	1
sub-052	30	2
sub-053	38	1
sub-054	21	1
sub-056	23	1
sub-057	27	1
sub-059	44	1
sub-062	36	1
sub-068	22	1
sub-069	30	1
sub-070	21	1
sub-071	21	1
sub-073	28	2
sub-074	21	2
sub-079	27	2
sub-080	33	2
sub-083	36	1
sub-085	23	1
sub-086	24	2
sub-089	25	1
sub-090	25	1
sub-091	41	1
sub-093	24	1
sub-096	22	2
sub-101	26	2
sub-103	18	1
sub-105	24	2
sub-119	35	2
sub-123	19	2
sub-125	26	1
sub-126	18	1
sub-127	22	1
sub-007	41	2
sub-008	39	2
sub-009	22	1
sub-012	23	1
sub-020	21	2
sub-035	24	1
sub-036	32	1
sub-037	27	2
sub-038	24	2
sub-039	20	2
sub-042	21	2
sub-044	22	1
sub-048	21	1
sub-049	52	1
sub-061	35	1
sub-064	30	2
sub-065	22	2
sub-066	19	2
sub-072	20	2
sub-075	25	1
sub-076	23	2
sub-077	22	2
sub-081	25	1
sub-082	27	1
sub-084	34	1
sub-087	22	1
sub-092	43	1
sub-094	28	2
sub-095	21	1
sub-097	21	2
sub-098	34	1
sub-100	26	2
sub-102	22	2
sub-104	22	1
sub-106	21	1
sub-107	21	1
sub-108	29	2
sub-109	24	2
sub-110	30	2
sub-111	29	2
sub-113	23	2
sub-114	23	1
sub-115	22	1
sub-116	22	2
sub-117	22	2
sub-118	18	1
sub-121	23	1
sub-122	22	1
sub-124	19	1
sub-128	22	2
sub-129	22	1
sub-130	20	1
sub-131	22	2
"""
    rows = []
    for line in missing_order_text.strip().splitlines():
        sid, age, gender = [x.strip() for x in line.split('\t')]
        if sid in missing_subjects:
            rows.append({"ID": sid, "age": float(age), "gender": float(gender)})
    missing_df = pd.DataFrame(rows)

    missing_path = Path(base) / "scripts/mri/rt_fmri_analysis/rt_missing_subjects.txt"
    missing_path.parent.mkdir(parents=True, exist_ok=True)
    missing_df.to_csv(missing_path, index=False, sep="\t")
    print("Wrote:", missing_path)

# Filter cov_table (keep SPM row order)
if spm_id_col in cov_table.columns:
    cov_table = cov_table[cov_table[spm_id_col].isin(complete_ids)]

Removing subjects with missing RT in any condition: sub-004, sub-006, sub-017, sub-034, sub-012, sub-104, sub-107, sub-117
Wrote: C:\Users\juhoffmann\Desktop\SubliminalVideoPriming\scripts\mri\rt_fmri_analysis\rt_missing_subjects.txt

In [161]:
cov_table

          ID       contrast    Condition  Age  Antidepressants  BDI        rt
2    sub-010  con_0001.nii'  happy_happy   22              0.0    0  0.599472
3    sub-011  con_0001.nii'  happy_happy   18              0.0    8  0.541878
4    sub-014  con_0001.nii'  happy_happy   26              0.0    0  0.588231
5    sub-015  con_0001.nii'  happy_happy   28              0.0    4  0.493879
8    sub-018  con_0001.nii'  happy_happy   22              0.0    0  0.856436
..       ...            ...          ...  ...              ...  ...       ...
443  sub-124  con_0003.nii'    sad_happy   18              1.0   36  0.476631
444  sub-128  con_0003.nii'    sad_happy   22              1.0   29  0.582500
445  sub-129  con_0003.nii'    sad_happy   22              0.0   25  0.517800
446  sub-130  con_0003.nii'    sad_happy   20              1.0   49  0.757017
447  sub-131  con_0003.nii'    sad_happy   22              1.0   32  0.819602

[408 rows x 7 columns]

In [162]:
# Build RT regressor files (ID, Age, Gender, rt) in SPM row order
# Age/Gender mapping from provided list
order_text = """

sub-004	29	2
sub-006	23	1
sub-010	23	2
sub-011	19	1
sub-014	27	2
sub-015	22	1
sub-016	18	2
sub-017	36	2
sub-018	26	2
sub-019	28	2
sub-022	29	2
sub-024	26	2
sub-025	22	1
sub-027	22	1
sub-028	32	1
sub-029	25	1
sub-030	23	1
sub-031	32	2
sub-032	22	2
sub-033	26	2
sub-034	21	2
sub-041	26	2
sub-043	21	1
sub-045	25	2
sub-046	33	1
sub-047	25	1
sub-050	30	1
sub-051	18	1
sub-052	30	2
sub-053	38	1
sub-054	21	1
sub-056	23	1
sub-057	27	1
sub-059	44	1
sub-062	36	1
sub-068	22	1
sub-069	30	1
sub-070	21	1
sub-071	21	1
sub-073	28	2
sub-074	21	2
sub-079	27	2
sub-080	33	2
sub-083	36	1
sub-085	23	1
sub-086	24	2
sub-089	25	1
sub-090	25	1
sub-091	41	1
sub-093	24	1
sub-096	22	2
sub-101	26	2
sub-103	18	1
sub-105	24	2
sub-119	35	2
sub-123	19	2
sub-125	26	1
sub-126	18	1
sub-127	22	1
sub-007	41	2
sub-008	39	2
sub-009	22	1
sub-012	23	1
sub-020	21	2
sub-035	24	1
sub-036	32	1
sub-037	27	2
sub-038	24	2
sub-039	20	2
sub-042	21	2
sub-044	22	1
sub-048	21	1
sub-049	52	1
sub-061	35	1
sub-064	30	2
sub-065	22	2
sub-066	19	2
sub-072	20	2
sub-075	25	1
sub-076	23	2
sub-077	22	2
sub-081	25	1
sub-082	27	1
sub-084	34	1
sub-087	22	1
sub-092	43	1
sub-094	28	2
sub-095	21	1
sub-097	21	2
sub-098	34	1
sub-100	26	2
sub-102	22	2
sub-104	22	1
sub-106	21	1
sub-107	21	1
sub-108	29	2
sub-109	24	2
sub-110	30	2
sub-111	29	2
sub-113	23	2
sub-114	23	1
sub-115	22	1
sub-116	22	2
sub-117	22	2
sub-118	18	1
sub-121	23	1
sub-122	22	1
sub-124	19	1
sub-128	22	2
sub-129	22	1
sub-130	20	1
sub-131	22	2
"""
age_map = {}
gender_map = {}
for line in order_text.strip().splitlines():
    sid, age, gender = [x.strip() for x in line.split('\t')]
    age_map[sid] = float(age)
    gender_map[sid] = float(gender)

rt_cols = [spm_id_col, "rt"]
rt_reg = cov_table[[c for c in rt_cols if c in cov_table.columns]].copy()
rt_reg["Age"] = rt_reg[spm_id_col].map(age_map)
rt_reg["Gender"] = rt_reg[spm_id_col].map(gender_map)

missing_age = rt_reg.loc[rt_reg["Age"].isna(), spm_id_col].dropna().unique().tolist()
missing_gender = rt_reg.loc[rt_reg["Gender"].isna(), spm_id_col].dropna().unique().tolist()
if missing_age:
    print("WARNING: Missing age for:", ', '.join(missing_age))
if missing_gender:
    print("WARNING: Missing gender for:", ', '.join(missing_gender))

# Warn if any missing RT
if "rt" in rt_reg.columns and rt_reg["rt"].isna().any():
    missing_ids = rt_reg.loc[rt_reg["rt"].isna(), spm_id_col].dropna().unique().tolist()
    print("WARNING: Missing RT for participants:", ', '.join(missing_ids))

# Output directory
rt_out_dir = Path(base) / "scripts/mri/rt_fmri_analysis"
rt_out_dir.mkdir(parents=True, exist_ok=True)

# CSV output (with header)
rt_csv_path = rt_out_dir / "rt_regressors.csv"
rt_reg[[spm_id_col, "Age", "Gender", "rt"]].to_csv(rt_csv_path, index=False)
print("Wrote:", rt_csv_path)

# TXT output (comma-separated, no header)
rt_txt_path = rt_out_dir / "rt_regressors.txt"
rt_reg[[spm_id_col, "Age", "Gender", "rt"]].to_csv(rt_txt_path, index=False, header=False, sep=",")
print("Wrote:", rt_txt_path)

WARNING: Missing columns for RT regressor output: Gender
Wrote: C:\Users\juhoffmann\Desktop\SubliminalVideoPriming\scripts\mri\rt_fmri_analysis\rt_regressors.csv
Wrote: C:\Users\juhoffmann\Desktop\SubliminalVideoPriming\scripts\mri\rt_fmri_analysis\rt_regressors.txt

In [163]:
cov_table.to_csv(out_path_regressor, index=False)
print("Wrote:", out_path_regressor  )

Wrote: C:\Users\juhoffmann\Desktop\SubliminalVideoPriming\scripts\mri\rt_fmri_analysis\regressors.csv

In [164]:
# SPM-ready covariate file (no ID column, no header)
spm_out_path = Path(base) / "scripts/mri/medication_severity_effect_MDD/regressors_spm.txt"
spm_cov_cols = [c for c in ["Age", "Antidepressants", "BDI", "rt"] if c in cov_table.columns]
cov_table_spm = cov_table[spm_cov_cols]
cov_table_spm.to_csv(spm_out_path, sep=",", header=False, index=False)
print("Wrote:", spm_out_path)

Wrote: C:\Users\juhoffmann\Desktop\SubliminalVideoPriming\scripts\mri\medication_severity_effect_MDD\regressors_spm.txt

In [165]:
# Patient-only regressor sheet (Age, Gender, Antidepressants, BDI)
patients_text = """
sub-007	41	2
sub-008	39	2
sub-009	22	1
sub-012	23	1
sub-020	21	2
sub-035	24	1
sub-036	32	1
sub-037	27	2
sub-038	24	2
sub-039	20	2
sub-042	21	2
sub-044	22	1
sub-048	21	1
sub-049	52	1
sub-061	35	1
sub-064	30	2
sub-065	22	2
sub-066	19	2
sub-072	20	2
sub-075	25	1
sub-076	23	2
sub-077	22	2
sub-081	25	1
sub-082	27	1
sub-084	34	1
sub-087	22	1
sub-092	43	1
sub-094	28	2
sub-095	21	1
sub-097	21	2
sub-098	34	1
sub-100	26	2
sub-102	22	2
sub-104	22	1
sub-106	21	1
sub-107	21	1
sub-108	29	2
sub-109	24	2
sub-110	30	2
sub-111	29	2
sub-113	23	2
sub-114	23	1
sub-115	22	1
sub-116	22	2
sub-117	22	2
sub-118	18	1
sub-121	23	1
sub-122	22	1
sub-124	19	1
sub-128	22	2
sub-129	22	1
sub-130	20	1
sub-131	22	2
"""
patients = []
for line in patients_text.strip().splitlines():
    sid, age, gender = [x.strip() for x in line.split('\t')]
    patients.append({"ID": sid, "Age": float(age), "Gender": float(gender)})
patients_df = pd.DataFrame(patients)

# Add medication and BDI from cov
med_col = "Antidepressants"
bdi_col = "BDI"
cov_subset = cov[[cov_id_col, med_col, bdi_col]].copy()
patients_df = patients_df.merge(cov_subset, left_on=spm_id_col, right_on=cov_id_col, how="left")
if cov_id_col in patients_df.columns and cov_id_col != spm_id_col:
    patients_df = patients_df.drop(columns=[cov_id_col])

# Warn if any medication/BDI missing
missing_med = patients_df.loc[patients_df[med_col].isna(), spm_id_col].tolist()
missing_bdi = patients_df.loc[patients_df[bdi_col].isna(), spm_id_col].tolist()
if missing_med:
    print("WARNING: Missing medication for:", ', '.join(missing_med))
if missing_bdi:
    print("WARNING: Missing BDI for:", ', '.join(missing_bdi))

# Output: keep order from patients_text
patient_out_path = Path(base) / "data/mri/patient_regressors.csv"
patients_df.to_csv(patient_out_path, index=False)
print("Wrote:", patient_out_path)

# SPM-ready (no header, no ID)
patient_spm_out = Path(base) / "scripts/mri/medication_severity_effect_MDD/patient_regressors_spm.txt"
patients_df[["Age", "Gender", med_col, bdi_col]].to_csv(patient_spm_out, sep=",", header=False, index=False)
print("Wrote:", patient_spm_out)

Wrote: C:\Users\juhoffmann\Desktop\SubliminalVideoPriming\data\mri\patient_regressors.csv
Wrote: C:\Users\juhoffmann\Desktop\SubliminalVideoPriming\scripts\mri\medication_severity_effect_MDD\patient_regressors_spm.txt

In [166]:
patients_df.head()

        ID   Age  Gender  Antidepressants  BDI
0  sub-007  41.0     2.0              1.0   26
1  sub-008  39.0     2.0              1.0   35
2  sub-009  22.0     1.0              1.0   14
3  sub-012  23.0     1.0              1.0   31
4  sub-020  21.0     2.0              1.0   32